#!/usr/bin/env python
"""Write Dakota input from external calibration data and run MCMC.

Observation data and cell indices must be prepared separately, e.g. with
``write_observations.py``. This script copies them into ``dakota_mcmc/``,
optionally builds or reuses a proposal covariance, writes ``sod_bayes.in``, and
runs::

    dakota -i <input_file> -o <output_file>

Example workflow::

    python dakota_mcmc/write_observations.py 0.9e5 0.9e4 0.9 0.1 --out-dir dakota_mcmc
    python dakota_mcmc/run_mcmc.py --obs dakota_mcmc/sod_obs.dat \\
        --cells dakota_mcmc/sod_cells.npy --forward euler
    python dakota_mcmc/run_mcmc.py --obs ... --cells ... \\
        --ensemble-dir training_data/shock_tube/enkf_ensemble_files
    python dakota_mcmc/run_mcmc.py --obs ... --cells ... --plot \\
        --plot-truth 0.9e5 0.9e4 0.9 0.1
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
HERE = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from common import (  # noqa: E402
    N_FIELD, PARAM_NAMES, T_FINAL, TRUTH, exact_density_on_cells,
    make_forward, make_plots,
)
from gen_proposal_cov import write_proposal_cov  # noqa: E402
DEFAULT_DAKOTA = Path.home() / "dakota-install" / "bin" / "dakota"
DEFAULT_INPUT = HERE / "sod_bayes.in"
DEFAULT_OUTPUT = HERE / "sod_bayes.out"
DEFAULT_CHAIN_OUT = HERE / "sod_chain.dat"
DEFAULT_SOD_OBS = HERE / "sod_obs.dat"
DEFAULT_SOD_CELLS = HERE / "sod_cells.npy"
DEFAULT_PROP_COV = HERE / "prop_cov.dat"

LOWER_BOUNDS = np.array([50000.0, 5000.0, 0.5, 0.075])
UPPER_BOUNDS = np.array([150000.0, 15000.0, 1.5, 0.17])


def calibration_terms_from_obs(obs_path: Path) -> int:
    """Return ``m`` from a Dakota freeform calibration file (densities + variances)."""
    row = np.atleast_1d(np.loadtxt(obs_path))
    if row.size % 2:
        raise ValueError(f"{obs_path}: expected an even number of columns "
                         f"(m densities + m variances), got {row.size}")
    return row.size // 2


def stage_calibration_files(obs_path: Path, cells_path: Path, *,
                            obs_dest: Path = DEFAULT_SOD_OBS,
                            cells_dest: Path = DEFAULT_SOD_CELLS) -> int:
    """Copy external obs/cell files into the Dakota working directory."""
    obs_path = obs_path.resolve()
    cells_path = cells_path.resolve()
    if not obs_path.is_file():
        raise FileNotFoundError(obs_path)
    if not cells_path.is_file():
        raise FileNotFoundError(cells_path)

    n_obs = calibration_terms_from_obs(obs_path)
    cell_idx = np.load(cells_path)
    if cell_idx.size != n_obs:
        raise ValueError(f"{cells_path} has {cell_idx.size} indices but "
                         f"{obs_path} implies {n_obs} calibration terms")

    obs_dest.parent.mkdir(parents=True, exist_ok=True)
    cells_dest.parent.mkdir(parents=True, exist_ok=True)
    if obs_path != obs_dest.resolve():
        shutil.copy2(obs_path, obs_dest)
    if cells_path != cells_dest.resolve():
        shutil.copy2(cells_path, cells_dest)
    return n_obs


def ensure_proposal_cov(*,
                        cov_path: Path | None,
                        ensemble_dir: Path | str | None = None,
                        cov_scale: float = 1.0,
                        dest: Path = DEFAULT_PROP_COV) -> Path:
    """Compute from ensemble, or reuse an existing covariance file."""
    if ensemble_dir is not None:
        write_proposal_cov(ensemble_dir=ensemble_dir, scale=cov_scale, out=dest)
        print(f"[cov]    computed from {ensemble_dir} -> {dest}")
        return dest

    source = cov_path.expanduser().resolve() if cov_path is not None else dest.resolve()
    if not source.is_file():
        raise FileNotFoundError(
            f"{source} not found -- pass --cov, run gen_proposal_cov.py first, "
            "or pass --ensemble-dir to compute from the HDF5 ensemble")
    if source != dest.resolve():
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, dest)
    print(f"[cov]    using {source}")
    return dest


def write_dakota_input(*,
                       initial_point: np.ndarray,
                       n_calibration: int,
                       chain_samples: int,
                       seed: int,
                       chain_out: Path,
                       input_path: Path = DEFAULT_INPUT) -> None:
    """Write ``sod_bayes.in`` with ``calibration_terms`` matching the obs file."""
    initial_point = np.asarray(initial_point, dtype=float)
    chain_name = chain_out.name
    text = f"""# Generated by run_mcmc.py -- do not edit by hand unless you know why.

environment
  tabular_data
    tabular_data_file 'sod_tabular.dat'

method
  bayes_calibration queso
    chain_samples = {chain_samples} seed = {seed}
    export_chain_points_file '{chain_name}'
    dram
    burn_in_samples = {int(0.2 * chain_samples)}  # 20% burn-in
    proposal_covariance
      file 'prop_cov.dat'
        matrix

variables
  uniform_uncertain 4
    descriptors   'p_high'  'p_low'  'rho_high'  'rho_low'
    lower_bounds   {LOWER_BOUNDS[0]:.1f}   {LOWER_BOUNDS[1]:.1f}    {LOWER_BOUNDS[2]:.1f}        {LOWER_BOUNDS[3]:.3f}
    upper_bounds  {UPPER_BOUNDS[0]:.1f}  {UPPER_BOUNDS[1]:.1f}    {UPPER_BOUNDS[2]:.1f}       {UPPER_BOUNDS[3]:.2f}
    initial_point {initial_point[0]:.1f}  {initial_point[1]:.1f}    {initial_point[2]:.2f}        {initial_point[3]:.3f}

interface
  fork
    analysis_drivers = 'sod_driver.sh'
    parameters_file = 'params.in'
    results_file    = 'results.out'

responses
  calibration_terms = {n_calibration}
    calibration_data_file = 'sod_obs.dat'
      freeform
      num_experiments = 1
      variance_type = 'scalar'
  no_gradients
  no_hessians
"""
    input_path.write_text(text)


def resolve_dakota(path: Path | None) -> Path:
    if path is not None:
        return path.expanduser()
    if DEFAULT_DAKOTA.is_file():
        return DEFAULT_DAKOTA
    found = shutil.which("dakota")
    if found is None:
        raise FileNotFoundError(
            "dakota executable not found -- pass --dakota or install to "
            f"{DEFAULT_DAKOTA}")
    return Path(found)


def run_dakota(*,
               dakota: Path,
               input_file: Path,
               output_file: Path,
               forward: str,
               cwd: Path = HERE) -> None:
    env = os.environ.copy()
    env["SOD_FORWARD"] = forward
    cmd = [str(dakota), "-i", input_file.name, "-o", output_file.name]
    print(f"[dakota] SOD_FORWARD={forward}  {' '.join(cmd)}  (cwd={cwd})")
    subprocess.run(cmd, cwd=cwd, env=env, check=True)


def load_obs_densities(path: Path) -> np.ndarray:
    """First half of a Dakota freeform row: observed densities only."""
    row = np.atleast_1d(np.loadtxt(path))
    if row.size % 2:
        raise ValueError(f"{path}: expected m densities + m variances, got {row.size}")
    return row[: row.size // 2]


def load_chain(path: Path) -> np.ndarray:
    """Read the 4 Sod-param columns from a Dakota exported chain file."""
    with open(path) as fh:
        header = fh.readline().lstrip("%").split()
    cols = [header.index(name) for name in PARAM_NAMES]
    return np.atleast_2d(np.loadtxt(path, skiprows=1, usecols=cols))


def plot_mcmc_results(*,
                      chain_path: Path,
                      forward: str,
                      obs_path: Path,
                      cells_path: Path,
                      outdir: Path = HERE,
                      burn: int = 0,
                      plot_truth: np.ndarray | None = None,
                      n_field_draws: int = 200,
                      seed: int = 0,
                      label: str = "dakota") -> None:
    """Marginals/traces + posterior field band via ``common.make_plots``."""
    chain_path = chain_path.resolve()
    if not chain_path.is_file():
        raise FileNotFoundError(f"chain not found: {chain_path}")

    chain = load_chain(chain_path)
    burn = min(int(burn), chain.shape[0])
    post = chain[burn:]
    truth = TRUTH if plot_truth is None else np.asarray(plot_truth, dtype=float)

    cell_idx = np.load(cells_path)
    obs_y = load_obs_densities(obs_path)

    mean = post.mean(axis=0)
    std = post.std(axis=0)
    quantiles = np.percentile(post, [2.5, 50, 97.5], axis=0)
    print(f"[plot]   chain {chain_path.name}: {chain.shape[0]} rows, "
          f"burn {burn} -> {post.shape[0]} kept")
    print("[plot]   posterior mean +/- std   [2.5%, 97.5%]   (truth):")
    for k, name in enumerate(PARAM_NAMES):
        print(f"    {name:9s} {mean[k]:.4e} +/- {std[k]:.2e}   "
              f"[{quantiles[0, k]:.4e}, {quantiles[2, k]:.4e}]   "
              f"(truth {truth[k]:.4e})")

    g_full = make_forward(forward, in_process=True)
    rng = np.random.default_rng(seed)
    n_draw = min(n_field_draws, post.shape[0])
    draw_idx = rng.choice(post.shape[0], size=n_draw, replace=False)
    fields = np.array([g_full(post[j]) for j in draw_idx])
    field_mean = fields.mean(axis=0)
    field_lo, field_hi = np.percentile(fields, [2.5, 97.5], axis=0)
    exact_rho = exact_density_on_cells(truth, T_FINAL, N_FIELD)
    post_rmse = float(np.sqrt(np.mean((field_mean - exact_rho) ** 2)))
    print(f"[plot]   posterior-mean density RMSE vs exact = {post_rmse:.4e}")

    res = {
        "chain": chain,
        "post": post,
        "truth": truth,
        "mean": mean,
        "std": std,
        "quantiles": quantiles,
        "acc_rate": 0.0,
        "x_cells": np.arange(N_FIELD) / N_FIELD,
        "exact": exact_rho,
        "field_mean": field_mean,
        "field_lo": field_lo,
        "field_hi": field_hi,
        "obs_x": cell_idx / N_FIELD,
        "obs_y": obs_y,
        "post_rmse": post_rmse,
        "burn": burn,
        "forward": forward,
    }
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    make_plots(res, outdir, label=label)


def prepare_and_run(*,
                    obs_path: Path,
                    cells_path: Path,
                    initial_point: np.ndarray,
                    dakota: Path | None = None,
                    input_file: Path = DEFAULT_INPUT,
                    output_file: Path = DEFAULT_OUTPUT,
                    chain_out: Path = DEFAULT_CHAIN_OUT,
                    forward: str = "euler",
                    cov_path: Path | None = None,
                    ensemble_dir: Path | str | None = None,
                    cov_scale: float = 1.0,
                    chain_samples: int = 5000,
                    seed: int = 12345,
                    run: bool = True) -> int:
    """Stage external inputs and optionally launch Dakota."""
    initial_point = np.asarray(initial_point, dtype=float)
    if initial_point.size != 4:
        raise ValueError(f"expected 4 Sod params for initial_point, got {initial_point.size}")

    n_calibration = stage_calibration_files(obs_path, cells_path)
    print(f"[obs]    staged {obs_path} -> {DEFAULT_SOD_OBS}")
    print(f"[cells]  staged {cells_path} -> {DEFAULT_SOD_CELLS}")
    print(f"[obs]    calibration_terms = {n_calibration}")

    ensure_proposal_cov(cov_path=cov_path, ensemble_dir=ensemble_dir,
                        cov_scale=cov_scale)

    write_dakota_input(initial_point=initial_point, n_calibration=n_calibration,
                       chain_samples=chain_samples, seed=seed,
                       chain_out=chain_out, input_path=input_file)
    print("[start]  " + "  ".join(f"{n}={initial_point[k]:.4e}"
                                    for k, n in enumerate(PARAM_NAMES)))
    print(f"[out]    wrote {input_file}")

    if run:
        exe = resolve_dakota(dakota)
        run_dakota(dakota=exe, input_file=input_file, output_file=output_file,
                   forward=forward)

    return n_calibration


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--obs", type=Path, required=True,
                    help="Dakota freeform calibration file (m densities + m variances)")
    ap.add_argument("--cells", type=Path, required=True,
                    help="observation cell indices (.npy), matching --obs")
    ap.add_argument("--initial-point", dest="initial_point", type=float, nargs=4,
                    default=list(TRUTH), metavar=tuple(PARAM_NAMES),
                    help="MCMC starting point (default: TRUTH, not the obs source)")
    ap.add_argument("--cov", type=Path, default=None,
                    help="proposal covariance file (default: prop_cov.dat when "
                         "--ensemble-dir is not given)")
    ap.add_argument("--dakota", type=Path, default=None,
                    help=f"dakota executable (default: {DEFAULT_DAKOTA} or PATH)")
    ap.add_argument("--input", type=Path, default=DEFAULT_INPUT,
                    help="Dakota input file to write")
    ap.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                    help="Dakota output file")
    ap.add_argument("--chain-out", dest="chain_out", type=Path, default=DEFAULT_CHAIN_OUT,
                    help="exported MCMC chain filename written into sod_bayes.in")
    ap.add_argument("--forward", choices=("exact", "euler", "surrogate"),
                    default="euler", help="SOD_FORWARD passed to sod_driver.py")
    ap.add_argument("--ensemble-dir", dest="ensemble_dir", default=None,
                    help="compute proposal covariance from this HDF5 ensemble "
                         "(overrides --cov / prop_cov.dat)")
    ap.add_argument("--cov-scale", dest="cov_scale", type=float, default=1.0,
                    help="scale factor when computing proposal covariance from ensemble")
    ap.add_argument("--chain-samples", dest="chain_samples", type=int, default=5000)
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--no-run", action="store_true",
                    help="write inputs only; do not invoke dakota")
    ap.add_argument("--plot", action="store_true",
                    help="after MCMC, plot marginals/traces and posterior field "
                         "(uses --chain-out; works with --no-run if chain exists)")
    ap.add_argument("--plot-burn", dest="plot_burn", type=int, default=200,
                    help="number of chain samples to discard before plotting")
    ap.add_argument("--plot-truth", dest="plot_truth", type=float, nargs=4,
                    default=None, metavar=tuple(PARAM_NAMES),
                    help="truth ICs for marginal/field overlays (default: TRUTH)")
    ap.add_argument("--plot-dir", dest="plot_dir", type=Path, default=HERE,
                    help="directory for dakota_marginals.png and dakota_field.png")
    ap.add_argument("--plot-field-draws", dest="plot_field_draws", type=int,
                    default=200, help="posterior draws used for the field band")
    args = ap.parse_args()

    prepare_and_run(obs_path=args.obs,
                    cells_path=args.cells,
                    initial_point=np.asarray(args.initial_point, dtype=float),
                    dakota=args.dakota,
                    input_file=args.input,
                    output_file=args.output,
                    chain_out=args.chain_out,
                    forward=args.forward,
                    cov_path=args.cov,
                    ensemble_dir=args.ensemble_dir,
                    cov_scale=args.cov_scale,
                    chain_samples=args.chain_samples,
                    seed=args.seed,
                    run=not args.no_run)

    if args.plot:
        plot_mcmc_results(chain_path=args.chain_out,
                          forward=args.forward,
                          obs_path=DEFAULT_SOD_OBS,
                          cells_path=DEFAULT_SOD_CELLS,
                          outdir=args.plot_dir,
                          burn=args.plot_burn,
                          plot_truth=(None if args.plot_truth is None
                                      else np.asarray(args.plot_truth, dtype=float)),
                          n_field_draws=args.plot_field_draws,
                          seed=args.seed)


if __name__ == "__main__":
    main()
